language: node_js
node_js:
- 16.13.1
script:
- npm test
- npm install
- npm run build
- gem install dpl

after_success:
- firebase deploy --token $FIREBASE_TOKEN
cache:
  directories:
  - node_modules
install:
- npm install -g firebase tools
deploy:
  provider: firebase
  cleanup: false
  token:
    secure: mU2OFeRtgBfjbVAsej96G0g1fNbgz6DSg++M1pX9xPonm9zzLvJSa3tVsYGJISJfPC5N8nJb1ltabBTnG93qh0At0pzjFiwSP3va7COn9nLd7Zh7de7GMiNoyiGhyTXOUnZklu2yESFeIpeojMg6Mp8Xe9P6yoXLOWWxmWUf3yEN1q9b7jwBMFQApmUOsxHSyYgUHjTwr2855iQnqYWVhlhNFfA5ae2pj0rUmidGeBzIg7cCgF6q2PqozpHBYrB6Ps5GjcANR6eG9/nK5sjKzwHmpxPjz1UWz3VCXUAEIIv/MNMNGhN3/GI6VNmx6Lc/UoWBzQ4gi9gjpHEVTXomRYqSJnfOb4LUCn0l7pfH3Ybe1F5aG2mXnPcEhnhzrlNmwdKiFXdsVqsw32QSV1FRLEYRw64xCf7efWa0cZywiKI0jmH6ig8jZ+fX3n0IgJGY4NEA4nRkPNo+tJQuoF2yyBFl/H8Wh+UzeYRxB9I3c18d6TxxPdfa29fm8C61bNrp77WgWZabJc03LeArU81Hue9bhucOTLAEQKqiYovM9QP2njSSxhtGVBnEXNtM412xk7kX8TZRMaJp4Y9v2pgP2UgsIShTBdPVzQRDC6US95TIZxC3tiU4FklEYYzbICBept4tARTKeOXNfNjlk4+9gNvfkAxKThTx2FYKTmx/ACI=
  on:
    branch: main
env:
  global:
    secure: mU2OFeRtgBfjbVAsej96G0g1fNbgz6DSg++M1pX9xPonm9zzLvJSa3tVsYGJISJfPC5N8nJb1ltabBTnG93qh0At0pzjFiwSP3va7COn9nLd7Zh7de7GMiNoyiGhyTXOUnZklu2yESFeIpeojMg6Mp8Xe9P6yoXLOWWxmWUf3yEN1q9b7jwBMFQApmUOsxHSyYgUHjTwr2855iQnqYWVhlhNFfA5ae2pj0rUmidGeBzIg7cCgF6q2PqozpHBYrB6Ps5GjcANR6eG9/nK5sjKzwHmpxPjz1UWz3VCXUAEIIv/MNMNGhN3/GI6VNmx6Lc/UoWBzQ4gi9gjpHEVTXomRYqSJnfOb4LUCn0l7pfH3Ybe1F5aG2mXnPcEhnhzrlNmwdKiFXdsVqsw32QSV1FRLEYRw64xCf7efWa0cZywiKI0jmH6ig8jZ+fX3n0IgJGY4NEA4nRkPNo+tJQuoF2yyBFl/H8Wh+UzeYRxB9I3c18d6TxxPdfa29fm8C61bNrp77WgWZabJc03LeArU81Hue9bhucOTLAEQKqiYovM9QP2njSSxhtGVBnEXNtM412xk7kX8TZRMaJp4Y9v2pgP2UgsIShTBdPVzQRDC6US95TIZxC3tiU4FklEYYzbICBept4tARTKeOXNfNjlk4+9gNvfkAxKThTx2FYKTmx/ACI=
