language: node_js

node_js:
  - "16.13.1"

script:
    - npm test
    - npm install
    - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
  
cache:
  directories:
    - node_modules

install:
   - npm install -g firebase tools

deploy:
  provider: firebase
  skip_cleanup: true
  token:
  secure: $FIREBASE_TOKEN
  project: "react-wearther-app-aml3304"
  on:
    branch: main