language: node_js

node_js:
  - "17.8.0"
sudo: false

script:
    - npm test
    - npm run build


cache:
  directories:
    - node_modules

install:
  - npm install

deploy:
  provider: firebase
  token:
    secure: "1//04FXNXDDae93OCgYIARAAGAQSNwF-L9Irjw2Zq33lm0HhInCzZAIJNLCOuTRlwg_2MuMh5ugomWEf7COeX4ocwiQF01YrsaJOOH4"